<template>
  <v-container>
    <v-row>
      <v-col>
        <HeroSection />
      </v-col>
    </v-row>
    <v-row>
      <v-col>
        <LazyAboutMe />
      </v-col>
    </v-row>
    <v-row>
      <v-col>
        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Laudantium harum magnam necessitatibus vel facere recusandae nulla qui perspiciatis provident, omnis porro architecto expedita blanditiis eos ratione unde est molestiae iusto dolorem fugit debitis minus earum mollitia. Voluptatum quisquam deleniti laborum, tenetur aut, officiis doloribus consequuntur autem soluta ducimus impedit cumque.</p>
        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Laudantium harum magnam necessitatibus vel facere recusandae nulla qui perspiciatis provident, omnis porro architecto expedita blanditiis eos ratione unde est molestiae iusto dolorem fugit debitis minus earum mollitia. Voluptatum quisquam deleniti laborum, tenetur aut, officiis doloribus consequuntur autem soluta ducimus impedit cumque.</p>
        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Laudantium harum magnam necessitatibus vel facere recusandae nulla qui perspiciatis provident, omnis porro architecto expedita blanditiis eos ratione unde est molestiae iusto dolorem fugit debitis minus earum mollitia. Voluptatum quisquam deleniti laborum, tenetur aut, officiis doloribus consequuntur autem soluta ducimus impedit cumque.</p>
        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Laudantium harum magnam necessitatibus vel facere recusandae nulla qui perspiciatis provident, omnis porro architecto expedita blanditiis eos ratione unde est molestiae iusto dolorem fugit debitis minus earum mollitia. Voluptatum quisquam deleniti laborum, tenetur aut, officiis doloribus consequuntur autem soluta ducimus impedit cumque.</p>
        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Laudantium harum magnam necessitatibus vel facere recusandae nulla qui perspiciatis provident, omnis porro architecto expedita blanditiis eos ratione unde est molestiae iusto dolorem fugit debitis minus earum mollitia. Voluptatum quisquam deleniti laborum, tenetur aut, officiis doloribus consequuntur autem soluta ducimus impedit cumque.</p>
        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Laudantium harum magnam necessitatibus vel facere recusandae nulla qui perspiciatis provident, omnis porro architecto expedita blanditiis eos ratione unde est molestiae iusto dolorem fugit debitis minus earum mollitia. Voluptatum quisquam deleniti laborum, tenetur aut, officiis doloribus consequuntur autem soluta ducimus impedit cumque.</p>
        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Laudantium harum magnam necessitatibus vel facere recusandae nulla qui perspiciatis provident, omnis porro architecto expedita blanditiis eos ratione unde est molestiae iusto dolorem fugit debitis minus earum mollitia. Voluptatum quisquam deleniti laborum, tenetur aut, officiis doloribus consequuntur autem soluta ducimus impedit cumque.</p>
        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Laudantium harum magnam necessitatibus vel facere recusandae nulla qui perspiciatis provident, omnis porro architecto expedita blanditiis eos ratione unde est molestiae iusto dolorem fugit debitis minus earum mollitia. Voluptatum quisquam deleniti laborum, tenetur aut, officiis doloribus consequuntur autem soluta ducimus impedit cumque.</p>
        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Laudantium harum magnam necessitatibus vel facere recusandae nulla qui perspiciatis provident, omnis porro architecto expedita blanditiis eos ratione unde est molestiae iusto dolorem fugit debitis minus earum mollitia. Voluptatum quisquam deleniti laborum, tenetur aut, officiis doloribus consequuntur autem soluta ducimus impedit cumque.</p>
        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Laudantium harum magnam necessitatibus vel facere recusandae nulla qui perspiciatis provident, omnis porro architecto expedita blanditiis eos ratione unde est molestiae iusto dolorem fugit debitis minus earum mollitia. Voluptatum quisquam deleniti laborum, tenetur aut, officiis doloribus consequuntur autem soluta ducimus impedit cumque.</p>
        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Laudantium harum magnam necessitatibus vel facere recusandae nulla qui perspiciatis provident, omnis porro architecto expedita blanditiis eos ratione unde est molestiae iusto dolorem fugit debitis minus earum mollitia. Voluptatum quisquam deleniti laborum, tenetur aut, officiis doloribus consequuntur autem soluta ducimus impedit cumque.</p>
        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Laudantium harum magnam necessitatibus vel facere recusandae nulla qui perspiciatis provident, omnis porro architecto expedita blanditiis eos ratione unde est molestiae iusto dolorem fugit debitis minus earum mollitia. Voluptatum quisquam deleniti laborum, tenetur aut, officiis doloribus consequuntur autem soluta ducimus impedit cumque.</p>
        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Laudantium harum magnam necessitatibus vel facere recusandae nulla qui perspiciatis provident, omnis porro architecto expedita blanditiis eos ratione unde est molestiae iusto dolorem fugit debitis minus earum mollitia. Voluptatum quisquam deleniti laborum, tenetur aut, officiis doloribus consequuntur autem soluta ducimus impedit cumque.</p>
        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Laudantium harum magnam necessitatibus vel facere recusandae nulla qui perspiciatis provident, omnis porro architecto expedita blanditiis eos ratione unde est molestiae iusto dolorem fugit debitis minus earum mollitia. Voluptatum quisquam deleniti laborum, tenetur aut, officiis doloribus consequuntur autem soluta ducimus impedit cumque.</p>
        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Laudantium harum magnam necessitatibus vel facere recusandae nulla qui perspiciatis provident, omnis porro architecto expedita blanditiis eos ratione unde est molestiae iusto dolorem fugit debitis minus earum mollitia. Voluptatum quisquam deleniti laborum, tenetur aut, officiis doloribus consequuntur autem soluta ducimus impedit cumque.</p>
        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Laudantium harum magnam necessitatibus vel facere recusandae nulla qui perspiciatis provident, omnis porro architecto expedita blanditiis eos ratione unde est molestiae iusto dolorem fugit debitis minus earum mollitia. Voluptatum quisquam deleniti laborum, tenetur aut, officiis doloribus consequuntur autem soluta ducimus impedit cumque.</p>
        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Laudantium harum magnam necessitatibus vel facere recusandae nulla qui perspiciatis provident, omnis porro architecto expedita blanditiis eos ratione unde est molestiae iusto dolorem fugit debitis minus earum mollitia. Voluptatum quisquam deleniti laborum, tenetur aut, officiis doloribus consequuntur autem soluta ducimus impedit cumque.</p>
        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Laudantium harum magnam necessitatibus vel facere recusandae nulla qui perspiciatis provident, omnis porro architecto expedita blanditiis eos ratione unde est molestiae iusto dolorem fugit debitis minus earum mollitia. Voluptatum quisquam deleniti laborum, tenetur aut, officiis doloribus consequuntur autem soluta ducimus impedit cumque.</p>
        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Laudantium harum magnam necessitatibus vel facere recusandae nulla qui perspiciatis provident, omnis porro architecto expedita blanditiis eos ratione unde est molestiae iusto dolorem fugit debitis minus earum mollitia. Voluptatum quisquam deleniti laborum, tenetur aut, officiis doloribus consequuntur autem soluta ducimus impedit cumque.</p>
        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Laudantium harum magnam necessitatibus vel facere recusandae nulla qui perspiciatis provident, omnis porro architecto expedita blanditiis eos ratione unde est molestiae iusto dolorem fugit debitis minus earum mollitia. Voluptatum quisquam deleniti laborum, tenetur aut, officiis doloribus consequuntur autem soluta ducimus impedit cumque.</p>
        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Laudantium harum magnam necessitatibus vel facere recusandae nulla qui perspiciatis provident, omnis porro architecto expedita blanditiis eos ratione unde est molestiae iusto dolorem fugit debitis minus earum mollitia. Voluptatum quisquam deleniti laborum, tenetur aut, officiis doloribus consequuntur autem soluta ducimus impedit cumque.</p>
        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Laudantium harum magnam necessitatibus vel facere recusandae nulla qui perspiciatis provident, omnis porro architecto expedita blanditiis eos ratione unde est molestiae iusto dolorem fugit debitis minus earum mollitia. Voluptatum quisquam deleniti laborum, tenetur aut, officiis doloribus consequuntur autem soluta ducimus impedit cumque.</p>
        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Laudantium harum magnam necessitatibus vel facere recusandae nulla qui perspiciatis provident, omnis porro architecto expedita blanditiis eos ratione unde est molestiae iusto dolorem fugit debitis minus earum mollitia. Voluptatum quisquam deleniti laborum, tenetur aut, officiis doloribus consequuntur autem soluta ducimus impedit cumque.</p>
        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Laudantium harum magnam necessitatibus vel facere recusandae nulla qui perspiciatis provident, omnis porro architecto expedita blanditiis eos ratione unde est molestiae iusto dolorem fugit debitis minus earum mollitia. Voluptatum quisquam deleniti laborum, tenetur aut, officiis doloribus consequuntur autem soluta ducimus impedit cumque.</p>
        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Laudantium harum magnam necessitatibus vel facere recusandae nulla qui perspiciatis provident, omnis porro architecto expedita blanditiis eos ratione unde est molestiae iusto dolorem fugit debitis minus earum mollitia. Voluptatum quisquam deleniti laborum, tenetur aut, officiis doloribus consequuntur autem soluta ducimus impedit cumque.</p>
        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Laudantium harum magnam necessitatibus vel facere recusandae nulla qui perspiciatis provident, omnis porro architecto expedita blanditiis eos ratione unde est molestiae iusto dolorem fugit debitis minus earum mollitia. Voluptatum quisquam deleniti laborum, tenetur aut, officiis doloribus consequuntur autem soluta ducimus impedit cumque.</p>
      </v-col>
    </v-row>
  </v-container>
</template>

<script>
export default {
  components: {}
};
</script>
